version: '3'

services:

  # Auth Service
  auth:
    image: auth-image
    container_name: auth_container
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    environment:
      - JWT_SECRET
      - MONGO_URI
      - MONGO_TEST_URI
    depends_on:
      - mongo
    ports:
      - 3001:3001
    volumes:
      - ./auth:/app

  # Database
  mongo:
    image: mongo:5.0.5
    container_name: database_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_AUTH_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_AUTH_PASS}
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: